use_frameworks!

target 'AJKitSwift_Example' do
  pod 'AJKitSwift',
  :subspecs => ['Foundation', 'UIKit'],
  :path => '../'

  target 'AJKitSwift_Tests' do
    inherit! :search_paths

    
  end
end
